<a href="https://colab.research.google.com/github/themehmi/Numpy-Projects/blob/main/dataset_sales_projectipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Finding Outliers using IQR**

In [25]:
import pandas as pd
import numpy as np
#fetch data from a url or csv
url="https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/sales.csv"
#printing dataset in form string data type to make it easier to understands
arr=np.genfromtxt(url, delimiter=',', dtype=str)
print("String Array:")
print(arr)
print("\n")
#now in the form of float data type to perform calculations and basic stats
arr1=np.genfromtxt(url, delimiter=',', skip_header=1, usecols=range(1,5))
print(arr1)

String Array:
[['Month' 'Sales' 'Profit' 'Units_Sold' 'Expenses']
 ['Jan' '2500' '600' '40' '1900']
 ['Feb' '2700' '600' '42' '2000']
 ['Mar' '3000' '5000' '50' '2200']
 ['Apr' '4520' '1100' '39' '2100']
 ['May' '3050' '1100' '41' '2600']
 ['Jun' '3170' '1250' '32' '2610']
 ['Jul' '3290' '1082' '29' '2760']
 ['Aug' '3410' '1217' '40' '2910']
 ['Sep' '3530' '1353' '42' '3060']
 ['Oct' '3650' '1488' '50' '3210']
 ['Nov' '3770' '1624' '39' '3360']
 ['Dec' '3890' '1759' '41' '3510']]


[[2500.  600.   40. 1900.]
 [2700.  600.   42. 2000.]
 [3000. 5000.   50. 2200.]
 [4520. 1100.   39. 2100.]
 [3050. 1100.   41. 2600.]
 [3170. 1250.   32. 2610.]
 [3290. 1082.   29. 2760.]
 [3410. 1217.   40. 2910.]
 [3530. 1353.   42. 3060.]
 [3650. 1488.   50. 3210.]
 [3770. 1624.   39. 3360.]
 [3890. 1759.   41. 3510.]]


In [17]:
import pandas as pd
import numpy as np
Sales=arr1[:,0]
Mean=np.mean(Sales)
print("Mean:")
print(Mean)

Mean:
3373.3333333333335


In [22]:
# percentiles
#p50=median
per25 = np.percentile(Sales, 25)
per50 = np.percentile(Sales, 50)# median
per75 = np.percentile(Sales, 75)
print("25th percentile:", per25)
print("50th percentile (median):", per50)
print("75th percentile:", per75)
#find the iqr
iqr = per75 - per25
print("Interquartile Range (IQR):", iqr)
#now we must define boundaries
lower_bound = per25 - 1.5 * iqr
upper_bound = per75 + 1.5 * iqr
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
#find the outliers
outliers = Sales[(Sales < lower_bound) | (Sales > upper_bound)]
print("Outliers:",outliers)

25th percentile: 3037.5
50th percentile (median): 3350.0
75th percentile: 3680.0
Interquartile Range (IQR): 642.5
Lower Bound: 2073.75
Upper Bound: 4643.75
Outliers: []


In [24]:
import pandas as pd
url="https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/sales.csv"
df=pd.read_csv(url)
df.describe()

Sales       Profit  Units_Sold     Expenses
count    12.000000    12.000000   12.000000    12.000000
mean   3373.333333  1514.416667   40.416667  2685.000000
std     551.845389  1152.429407    5.991787   546.434725
min    2500.000000   600.000000   29.000000  1900.000000
25%    3037.500000  1095.500000   39.000000  2175.000000
50%    3350.000000  1233.500000   40.500000  2685.000000
75%    3680.000000  1522.000000   42.000000  3097.500000
max    4520.000000  5000.000000   50.000000  3510.000000