<a href="https://colab.research.google.com/github/themehmi/Numpy-Projects/blob/main/Numpy_Projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Expense Tracker**

In [ ]:
#Create an array of 28 random expenses between $10 and $200
import numpy as np
expenses = np.random.randint(10,200,28)
print("Expenses:",expenses)
#Calculate total of monthly expenses using np.sum() function
MaxExpense = np.sum(expenses)
print("Total expense for the month:",MaxExpense)
#Average daily expense
AverageExpense = MaxExpense/28
print("Average expense per day:",AverageExpense)
#print day with maxm expense
print("Day with max expense:",np.argmax(expenses))
#Total expense per week (split into 4 weeks, hint: reshape or slice)
expenses_per_week = expenses.reshape(4,7)
print("Expenses per week:",expenses_per_week)

Expenses: [ 33 153 189  87 194 134 120 186 185 100 145 188  62 182 175  97  82  48
  92 152  39  60  20  10  44  20 153  15]
Total expense for the month: 2965
Average expense per day: 105.89285714285714
Day with max expense: 4
Expenses per week: [[ 33 153 189  87 194 134 120]
 [186 185 100 145 188  62 182]
 [175  97  82  48  92 152  39]
 [ 60  20  10  44  20 153  15]]


**Correlation Tool**

In [ ]:
# Sequential arrays
import numpy as np
array1 = np.arange(1,21)
array2 = np.arange(21,41)
print("Array 1:", array1)
print("Array 2:", array2)
#Assign Values of Array 1 and 2 into variables X and Y respectively..
X=array1
Y=array2
#calculate covariance "Covariance = mean((X - mean(X)) × (Y - mean(Y)))"
MeanX = np.mean(X)
MeanY = np.mean(Y)
Covariance = np.mean((X - MeanX)*(Y - MeanY))
print("Covariance:",Covariance)
#Calculate Standard Deviation for both arrays
StdX = np.std(X)
StdY = np.std(Y)
#Find Correlation without using corrcoef() function
Correlation = Covariance/(StdX*StdY)
print("Correlation:",Correlation)
#verify your answer using corrcoef()
print("Correlation using corrcoef():",np.corrcoef(X,Y))


Array 1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array 2: [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
Covariance: 33.25
Correlation: 0.9999999999999998
Correlation using corrcoef(): [[1. 1.]
 [1. 1.]]
